version: '2'

services:
#  proxy:
#    container_name: 'traefik'
#    image: traefik:1.5
#    restart: always
#    ports:
#      - '8600:80'
#    networks:
#      - proxy
#    volumes:
#      - '/var/run/docker.sock:/var/run/docker.sock'
#      - './traefik.toml:/traefik.toml'

  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - '/mnt/data/portainer:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'

  media:
    container_name: 'media'
    image: madslundt/cloud-media-scripts
    restart: always
    privileged: true
    devices:
      - /dev/fuse
    cap_add:
      - CAP_MKNOD
      - CAP_SYS_ADMIN
    environment:
      ENCRYPT_MEDIA: 0
      PUID: 1000
      PGID: 1000
    volumes:
      - '/mnt/data/media/unionfs:/local-media:shared'
      - '/mnt/data/media/decrypt:/local-decrypt:shared'
      - '/mnt/data/media/config:/config'
      - '/mnt/data/media/chunks:/chunks'
      - '/mnt/data/media/db:/data/db'
      - '/mnt/data/media/logs:/data/logs'


  rutorrent:
    container_name: 'rutorrent'
    image: linuxserver/rutorrent:latest
    restart: always
    depends_on:
      - media
    ports:
      - '5000:5000'
      - '51413:51413'
      - '6881:6881/udp'
      - '8080:80'
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Europe/Copenhagen'
    volumes:
      - '/mnt/data/rutorrent/config:/config'
      - '/mnt/data/rutorrent/downloads:/downloads'


  sonarr:
    container_name: 'sonarr'
    image: linuxserver/sonarr:latest
    restart: always
    depends_on:
      - media
      - rutorrent
    ports:
      - '8989:8989'
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Europe/Copenhagen'
    volumes:
      - '/mnt/data/sonarr/config:/config'
      - '/mnt/data/media/unionfs:/tv'
      - '/mnt/data/rutorrent/downloads:/downloads'


  radarr:
    container_name: 'radarr'
    image: linuxserver/radarr:latest
    restart: always
    depends_on:
      - media
      - rutorrent
    ports:
      - '7878:7878'
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Europe/Copenhagen'
    volumes:
      - '/mnt/data/radarr/config:/config'
      - '/mnt/data/media/unionfs:/tv'
      - '/mnt/data/rutorrent/downloads:/downloads'


  jackett:
    container_name: 'jacket'
    image: linuxserver/jackett:latest
    restart: always
    ports:
      - '9117:9117'
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Europe/Copenhagen'
    volumes:
      - '/mnt/data/jackett/config:/config'
      - '/mnt/data/jackett/blackhole:/downloads'

  plex:
    container_name: 'plex'
    image: linuxserver/plex:latest
    restart: always
    depends_on:
      - media
    ports:
      - '32400:32400'
      - '32400:32400/udp'
      - '32469:32469'
      - '32469:32469/udp'
      - '5353:5353/udp'
      - '1900:1900/udp'
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Europe/Copenhagen'
      VERSION: 'latest'
    volumes:
      - '/mnt/data/plex/config:/config'
      - '/mnt/data/media/unionfs:/unionfs'
      - '/mnt/data/plex/transcode:/transcode'